package com.mayer.mybatis.crud.dao;

import com.mayer.mybatis.crud.beans.Department;
import com.mayer.mybatis.crud.beans.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    Department selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_department
     *
     * @mbg.generated Wed Sep 13 23:04:22 CST 2017
     */
    int updateByPrimaryKey(Department record);
}